replicaCount: 1

image:
  repository: ghcr.io/yong-king/my-nginx
  tag: "1.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

imagePullSecrets:
  - name: ghcr-secret   # 这里填你创建的 secret 名称
